site_name: MkAPI
site_author: daizutabi
site_description: API documentation with MkDocs.
site_url: https://daizutabi.github.io/mkapi/
repo_url: https://github.com/daizutabi/mkapi/
repo_name: daizutabi/mkapi
edit_uri: edit/main/docs/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
plugins:
  - search:
  - mkapi:
      enabled: true
      config: config.py
      debug: true
      exclude:
        - _example
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - MkAPI: index.md
  - Usage:
      - Writing Docstrings: usage/writing.md
      - usage/object.md
      - usage/page.md
      - usage/config.md
  - Reference:
      - $api:src/mkapi.***
  - Example: $api:src/example.***
watch:
  - src/mkapi/css
  - src/mkapi/javascript
  - src/mkapi/templates
