site_name: MkAPI
site_url: https://daizutabi.github.io/mkapi/
site_description: API documentation with MkDocs.
site_author: daizutabi
repo_url: https://github.com/daizutabi/mkapi/
edit_uri: ""
theme:
  name: material
  features:
    - content.tooltips
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
plugins:
  - search:
  - mkapi:
      src_dirs: [.]
      filters: [plugin_filter]
      exclude: [.tests]
      page_title: custom.page_title
      section_title: custom.section_title
      # on_config: custom.on_config

nav:
  - index.md
  # - <api>/mkapi.objects|nav_filter1|nav_filter2
  - Section:
    - 1.md
    # - <api2>/mkapi.**|nav_filter3
    - 2.md
  # - MkDocs: <api3>/mkdocs.**|nav_filter4
  # - Polars: <api4>/polars.dataframe.***|nav_filter4
  - Polars: <api4>/polars.***|nav_filter4


extra_css:
  - custom.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.magiclink