name: Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Verify version match
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          PYPROJECT_VERSION=$(grep -m 1 "version = " pyproject.toml | cut -d'"' -f2)
          if [ "$TAG" != "$PYPROJECT_VERSION" ]; then
            echo "Error: Git tag ($TAG) does not match pyproject.toml version ($PYPROJECT_VERSION)"
            exit 1
          fi
          echo "Version verified: $TAG"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install uv
        run: pip install uv
      - name: Install the project
        run: uv sync
      - name: Build the project
        run: uv build --no-sources
      - name: Upload the project to PyPI
        run: uv publish
